name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout je repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Installeer dependencies
        run: npm install

      - name: Bouw de website
        run: npm run build
        env:
          # De PUBLIC_API_URL is de enige die we hier nodig hebben
          PUBLIC_API_URL: ${{ secrets.PUBLIC_API_URL }}

      - name: Deploy naar gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist